FROM php:8.4-cli-alpine

RUN apk add --no-cache libpq sqlite-libs postgresql-dev sqlite-dev unzip git \
    && docker-php-ext-install pdo_pgsql pdo_sqlite \
    && apk del postgresql-dev sqlite-dev

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
WORKDIR /app
EXPOSE 8000
